kind: pipeline
name: default

steps:
  - name: build_build_image
    image: plugins/docker
    settings:
      repo: sloong/sloongnet_build
      cache_from: sloong/sloongnet_build
      use_cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: build/Build.Dockerfile
      tags:
        - latest

  - name: build_run_image
    image: plugins/docker
    settings:
      repo: sloong/sloongnet_run
      cache_from: sloong/sloongnet_run
      use_cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: build/Run.Dockerfile
      tags:
        - latest

  - name: build
    image: sloong/sloongnet_build
    commands:
      - build/build.sh -ci

  - name: build_docker
    image: plugins/docker
    settings:
      repo: sloong/sloongnet
      cache_from: sloong/sloongnet
      use_cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - develop
    when:
      event: push
      branch: develop

  - name: release_docker
    image: plugins/docker
    settings:
      repo: sloong/sloongnet
      cache_from: sloong/sloongnet
      use_cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    when:
      event: push
      branch: master
