version: '3.2'
services:
  controller:
    image: sloong/sloongnet:latest
    container_name: controller
    command:
      - Manager
      - 0.0.0.0:8000
    ports:
      - "18000:8000"
    volumes:
      - "control_local:/data"
    networks:
      - sloongnet
    deploy:
      mode: replicated
      replicas: 1

  moduler:
    image: sloong/sloongnet:latest
    container_name: moduler
    ports:
      - "18002:8000"
    volumes:
      - "control_local:/data"
    networks:
      - sloongnet
    depends_on:
      - controller
    deploy:
      mode: replicated
      replicas: 1

  control-ui:
    image: sloong/sloongnet-webui
    container_name: control-ui
    ports:
      - "8000:8000"
    volumes:
      - type: volume
        source: webui_local
        target: /data
        volume:
          nocopy: true
    networks:
      - sloongnet
    deploy:
      mode: replicated
      replicas: 1
       
volumes:
  control_local:
  module_local:
  webui_local:

networks:
  sloongnet:
