version: '3.2'
services:
  controller:
    image: sloong/sloongnet:latest
    command:
      - Manager
      - 0.0.0.0:8000
    volumes:
      - "control_local:/data"
    restart: always
    networks:
      - sloongnet
    deploy:
      mode: replicated
      replicas: 1

  gateway:
    image: sloong/sloongnet:latest
    command:
      - Worker
      - controller:8000
      - --include=Gateway
    ports:
      - "18002:8000"
    volumes:
      - "module_local:/data"
    restart: always
    networks:
      - sloongnet
    depends_on:
      - controller
    deploy:
      mode: replicated
      replicas: 1
  
  moduler:
    image: sloong/sloongnet:latest
    command:
      - Worker
      - controller:8000
      - --exclude=Gateway,Processer
    volumes:
      - "module_local:/data"
    restart: always
    networks:
      - sloongnet
    depends_on:
      - controller
    deploy:
      mode: replicated
      replicas: 2

  ui:
    image: sloongnet-webui
    ports:
      - "8000:8000"
    volumes:
      - "webui_local:/data"
    restart: always
    networks:
      - sloongnet
    deploy:
      mode: replicated
      replicas: 1
       
volumes:
  control_local:
  module_local:
  webui_local:

networks:
  sloongnet:
